### ISSUE TITLE
tinyc2 cannot be used in C code

### ISSUE THREAD

**Issue by mmozeiko** [RandyGaul/tinyheaders#17]
In few places it uses C++ syntax:
* `true` bool literal in line 802
* C++11 list initialization in line 1422
* C++11 list initialization in line 1459 (from C2_PLANE_AT macro)

**Comment by RandyGaul** [comment]
Oh thanks for these catches! I've been using MSCV that does non-standard support even though the C compiler gets invoked -- so these are pretty helpful. How did you find them? Did you run gcc with some warning flags?

**Comment by mmozeiko** [comment]
I found these issues when I compiled my C file with MSVC. Just have main.c that includes tinyc2.h and you'll see errors I mentioned.

If I compile with gcc, I get few more errors:
```
tinyc2.h:519:1: error: multiple storage classes in declaration specifiers
 static C2_INLINE void c2MakeProxy( const void* shape, C2_TYPE type, c2Proxy* p )
 ^~~~~~
tinyc2.h:558:1: error: multiple storage classes in declaration specifiers
 static C2_INLINE int c2Support( const c2v* verts, int count, c2v d )
 ^~~~~~
tinyc2.h:580:1: error: multiple storage classes in declaration specifiers
 static C2_INLINE c2v c2L( c2Simplex* s )
 ^~~~~~
tinyc2.h:592:1: error: multiple storage classes in declaration specifiers
 static C2_INLINE void c2Witness( c2Simplex* s, c2v* a, c2v* b )
 ^~~~~~
tinyc2.h:604:1: error: multiple storage classes in declaration specifiers
 static C2_INLINE c2v c2D( c2Simplex* s )
 ^~~~~~
tinyc2.h:620:1: error: multiple storage classes in declaration specifiers
 static C2_INLINE void c22( c2Simplex* s )
 ^~~~~~
tinyc2.h:651:1: error: multiple storage classes in declaration specifiers
 static C2_INLINE void c23( c2Simplex* s )
 ^~~~~~
tinyc2.h: At top level:
tinyc2.h:1444:1: error: multiple storage classes in declaration specifiers
 static C2_INLINE c2v c2CapsuleSupport( c2Capsule A, c2v dir )
 ^~~~~~
tinyc2.h: At top level:
tinyc2.h:1557:1: error: multiple storage classes in declaration specifiers
 static C2_INLINE void c2Incident( c2v* incident, const c2Poly* ip, c2x ix, const c2Poly* rp, c2x rx, int re )
 ^~~~~~
```

**Comment by RandyGaul** [comment]
Ok great, I'll fix these up sometime soon and add you as a contributor. For now if you want to mess with the header just make some local changes :)

**Comment by felipefs** [comment]
You can use ```true``` as long as you include ```<stdbool.h>```

I'm checking how do I get the errors ```multiple storage classes in declaration specifiers```.

**Comment by mmozeiko** [comment]
Yes, sure you can include stdbool.h for bool/true/false, but then dup should be bool, not int. And instead 0 it should be initialized with true :)

These gcc errors i posted is from Windows gcc, not Linux. On Linux _WIN32 is not defined, so that #ifdef chooses correct C2_INLINE value - with attribute always_inline.

**Comment by felipefs** [comment]
> These gcc errors i posted is from Windows gcc, not Linux. On Linux _WIN32 is not defined, so that #ifdef chooses correct C2_INLINE value - with attribute always_inline.

Ok. Then the behaviour might be different on Linux (or it's a different GCC version). I was getting the following warning for every function with ```C2_INLINE```:

```
warning: always_inline function might not be inlinable [-Wattributes]
 C2_INLINE ...
```
I found on [GCC docs](https://gcc.gnu.org/onlinedocs/gcc/Inline.html) the following sintax:

> GCC does not inline any functions when not optimizing unless you specify the ‘always_inline’ attribute for the function, like this:
> ```c
> /* Prototype.  */
> inline void foo (const char) __attribute__((always_inline));
> ```

So I added the ```inline``` before the ```__attribute__```:

```c
#else
	#define C2_INLINE __attribute__((always_inline))
#endif
```
Changed to:
```c
#else
	#define C2_INLINE inline __attribute__((always_inline))
#endif
```

The inline warning was solved.

Platform: Linux
Compiler: gcc 6.3.1

**Comment by mmozeiko** [comment]
That still doesn't fix GCC for Windows.
Proper way would be to change it to:
```
